#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
modules/stages/generation_stage.py

Conformer generation stage.  Strictly generation only — no optimisation,
no pruning, no forcefield minimisation beyond what is intrinsic to the
generator (e.g. RDKit MMFF energy evaluation for sorting purposes).

=========================================================================
INPUT
=========================================================================

  stage_input : cleaned.csv from CleaningStage
    Required columns: inchi_key, smiles
    Optional: charge, mol_name

=========================================================================
OUTPUT  (canonical stage output)
=========================================================================

  energies.json   — ConformerSet JSON
    One entry per generated conformer.

=========================================================================
AUXILIARY OUTPUTS
=========================================================================

  summary.csv
  generation_metadata.json
  xyz/<inchi_key>_conf<NNN>.xyz

=========================================================================
BACKENDS
=========================================================================

  rdkit      — ETKDGv3 embedding + MMFF94/UFF energy evaluation
               (energy is the FF energy at the generated geometry, not an
                optimisation — geometry is not updated)
  crest      — Single RDKit seed → CREST iMTD-GC conformer search
               Energy read from XYZ comment line (absolute GFN2-xTB Ha).
               Requires CREST v2 executable (flag-based API).
  openbabel  — RDKit seed → obabel CLI --conformer GA
               MMFF94 energy evaluated after generation via RDKit.
               Requires obabel on PATH or configured via config["openbabel"]["executable"].

=========================================================================
PARALLELISM
=========================================================================

  Uses BaseStage.run_parallel() for all backends.
  n_workers and cores_per_item injected by PipelineRunner, then adjusted
  in execute() using generation_defaults.json:

    cores_per_item[engine]  caps cores_per_item allocated by resource allocator
    parallel[engine]        if false, forces n_workers=1 (effectively serial)

  All backends run as module-level worker functions (_worker_rdkit etc.)
  dispatched through the single picklable entry point _generation_worker().

=========================================================================
ADDING A BACKEND
=========================================================================

  1. Add entry: GENERATION_BACKENDS["mybackend"] = "_worker_mybackend"
  2. Add dispatch branch in _generation_worker()
  3. Implement module-level _worker_mybackend(args: dict) -> dict
     args contains (from _base_args + _build_args):
       item_id, inchi_key, smiles, charge, multiplicity, seed, cores_per_item,
       num_confs, xyz_out_dir, workdir, log_path, checkpoints_dir,
       timestamp, stage, outputs_dir,
       <plus any tool paths, e.g. crest_exe, obabel_exe>
     Must return:
       item_id, status ("ok"|"failed"), log_details (list of (k,v) tuples),
       worker_name, worker_pid,
       conformers (list of ConformerRecord.to_dict()),
       error (str, only when status=="failed")
  4. Add cores_per_item and parallel entries in generation_defaults.json
  5. Add exe resolution in GenerationStage._build_args() if needed
  6. Add version detection in GenerationStage._get_tool_versions() if needed

=========================================================================
ITEM TRACKING
=========================================================================

  Items are inchi_keys (one per unique molecule in the CSV).
  Multiple rows with the same inchi_key are collapsed to one item.

=========================================================================
STRICT MODE
=========================================================================

  Hierarchy (highest wins):
    1. parameters["strict"]              runtime override
    2. generation_defaults.json "strict" stage default
    3. False                             fallback

  When True, any per-molecule failure aborts the pool immediately.

=========================================================================
XYZ COMMENT LINE FORMAT
=========================================================================

  All XYZ files written by this stage use the format:
    Generated by GenerationStage | engine=<engine> | E=<energy> <units>

  For CREST, the energy is the absolute GFN2-xTB energy in Hartree.
  For RDKit and OpenBabel, the energy is the MMFF94/UFF energy in kcal/mol.

"""

import json
import multiprocessing
import os
import shutil
import subprocess
from datetime import datetime

import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem, rdMolDescriptors

from modules.stages.base_stage import BaseStage
from modules.utils.atomic_write import AtomicWriter
from modules.utils.conformers import ConformerRecord, ConformerSet
from modules.utils.log_helper import LogHelper


# =============================================================================
# Registry
# =============================================================================

GENERATION_BACKENDS = {
    "rdkit":     "_worker_rdkit",
    "crest":     "_worker_crest",
    "openbabel": "_worker_openbabel",
}


# =============================================================================
# Module-level helpers — pure functions, picklable, used inside workers
# =============================================================================

def _write_xyz(mol, conf_id, path, engine, energy=None, energy_units="kcal/mol"):
    """Write a single conformer to XYZ format with standardised comment line."""
    conf  = mol.GetConformer(conf_id)
    atoms = list(mol.GetAtoms())
    comment = (
        f"Generated by GenerationStage | engine={engine} | "
        f"E={energy:.8f} {energy_units}"
        if energy is not None
        else f"Generated by GenerationStage | engine={engine}"
    )
    with open(path, "w") as f:
        f.write(f"{len(atoms)}\n{comment}\n")
        for atom in atoms:
            pos = conf.GetAtomPosition(atom.GetIdx())
            f.write(f"{atom.GetSymbol()} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}\n")


def _write_xyz_from_lines(natoms, atom_lines, path, engine, energy=None, energy_units="Ha"):
    """Write a conformer to XYZ format from raw atom lines (used by CREST parser)."""
    comment = (
        f"Generated by GenerationStage | engine={engine} | "
        f"E={energy:.8f} {energy_units}"
        if energy is not None
        else f"Generated by GenerationStage | engine={engine}"
    )
    with open(path, "w") as f:
        f.write(f"{natoms}\n{comment}\n")
        for line in atom_lines:
            f.write(line + "\n")


def _parse_multimodel_xyz(path):
    """
    Parse a multi-model XYZ file into a list of
    (natoms, comment_line, atom_lines) tuples.
    """
    result = []
    try:
        with open(path) as f:
            lines = [l.rstrip("\n") for l in f]
    except Exception:
        return result
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if not line:
            i += 1
            continue
        try:
            natoms = int(line)
        except ValueError:
            i += 1
            continue
        comment    = lines[i + 1] if i + 1 < len(lines) else ""
        atom_lines = lines[i + 2: i + 2 + natoms]
        if len(atom_lines) == natoms:
            result.append((natoms, comment, atom_lines))
        i += 2 + natoms
    return result


def _split_crest_xyz(crest_xyz, inchi_key, smiles, xyz_out_dir,
                     timestamp, source_row, charge, multiplicity, gfn_mode, crest_version):
    """
    Parse crest_conformers.xyz (multi-model XYZ) and write individual
    conformer XYZ files.  Returns list of ConformerRecord.to_dict().
    """
    records = []
    try:
        with open(crest_xyz) as f:
            lines = [l.rstrip("\n") for l in f]
    except Exception:
        return records

    i = conf_num = 0
    n_lines = len(lines)

    while i < n_lines:
        try:
            natoms = int(lines[i].strip())
        except ValueError:
            i += 1
            continue
        if i + 1 >= n_lines:
            break

        comment_line = lines[i + 1]
        atom_lines   = lines[i + 2: i + 2 + natoms]
        if len(atom_lines) < natoms:
            break

        try:
            energy = float(comment_line.strip())
        except ValueError:
            energy = None

        xyz_path = os.path.join(xyz_out_dir, f"{inchi_key}_conf{conf_num:03d}.xyz")
        _write_xyz_from_lines(
            natoms      = natoms,
            atom_lines  = atom_lines,
            path        = xyz_path,
            engine      = f"crest_{gfn_mode}",
            energy      = energy,
            energy_units = "Ha",
        )

        record = _make_record(
            inchi_key = inchi_key,
            conf_num  = conf_num,
            xyz_path  = xyz_path,
            energy    = energy,
            smiles    = smiles,
            provenance = {
                "backend":              "crest",
                "crest_version":        crest_version,
                "gfn":                  gfn_mode,
                "generation_timestamp": timestamp,
                "source_row":           source_row,
                "charge":               charge,
                "multiplicity":         multiplicity,
            },
        )
        records.append(record.to_dict())
        conf_num += 1
        i += 2 + natoms

    return records


def _make_record(inchi_key, conf_num, xyz_path, energy, smiles, provenance):
    """
    Build a ConformerRecord and append the required optimisation_history entry.
    Returns the ConformerRecord instance.
    """
    record = ConformerRecord(
        inchi_key  = inchi_key,
        conf_num   = conf_num,
        xyz_path   = xyz_path,
        energy     = energy,
        smiles     = smiles,
        provenance = provenance,
    )
    record.optimisation_history.append({
        "stage":     "generation",
        "engine":    provenance.get("backend", "unknown"),
        "energy":    energy,
        "xyz_path":  xyz_path,
        "timestamp": provenance.get("generation_timestamp", ""),
    })
    return record


# =============================================================================
# Module-level entry point — single picklable worker dispatched by run_parallel
# =============================================================================

def _generation_worker(args: dict) -> dict:
    """
    Dispatch to the correct backend worker based on args["engine"].
    This is the only function submitted to ProcessPoolExecutor.
    """
    engine = args.get("engine", "rdkit")
    if engine == "rdkit":
        return _worker_rdkit(args)
    if engine == "crest":
        return _worker_crest(args)
    if engine == "openbabel":
        return _worker_openbabel(args)
    return {
        "item_id":     args.get("item_id", "unknown"),
        "status":      "failed",
        "error":       f"Unknown generation engine: '{engine}'",
        "log_details": [],
        "worker_name": multiprocessing.current_process().name,
        "worker_pid":  os.getpid(),
        "conformers":  [],
    }


# =============================================================================
# Backend workers — module-level, picklable
# =============================================================================

def _worker_rdkit(args: dict) -> dict:
    """
    ETKDGv3 embedding + MMFF94/UFF energy evaluation.
    Energy is evaluated at the generated geometry — no optimisation.
    """
    worker_name = multiprocessing.current_process().name
    worker_pid  = os.getpid()

    inchi_key      = args["inchi_key"]
    smiles         = args["smiles"]
    charge         = args["charge"]
    multiplicity   = args["multiplicity"]
    seed           = args["seed"]
    cores_per_item = args["cores_per_item"]
    num_confs      = args["num_confs"]
    xyz_out_dir    = args["xyz_out_dir"]
    timestamp      = args["timestamp"]
    rdkit_version  = args.get("rdkit_version")

    os.makedirs(xyz_out_dir, exist_ok=True)

    # SMILES → mol with sanitize=False fallback (matches IC pipeline lines 156-164)
    raw_mol = Chem.MolFromSmiles(smiles)
    if raw_mol is None:
        raw_mol = Chem.MolFromSmiles(smiles, sanitize=False)
        if raw_mol is not None:
            raw_mol.UpdatePropertyCache(strict=False)
    if raw_mol is None:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": f"RDKit could not parse SMILES: {smiles}", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }
    mol = Chem.AddHs(raw_mol)

    emb = AllChem.ETKDGv3()
    emb.randomSeed            = seed
    emb.numThreads            = cores_per_item
    emb.useSmallRingTorsions  = True
    emb.useMacrocycleTorsions = True
    emb.enforceChirality      = True

    try:
        conf_ids = AllChem.EmbedMultipleConfs(mol, num_confs, emb)
    except Exception as e:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": f"Embedding failed: {e}", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    # Retry with random coords if fewer conformers were generated than requested
    # (matches IC pipeline lines 1069-1072)
    if len(conf_ids) < num_confs:
        try:
            emb_retry           = AllChem.ETKDGv3()
            emb_retry.randomSeed            = seed
            emb_retry.numThreads            = cores_per_item
            emb_retry.useSmallRingTorsions  = True
            emb_retry.useMacrocycleTorsions = True
            emb_retry.enforceChirality      = True
            emb_retry.useRandomCoords       = True
            conf_ids = AllChem.EmbedMultipleConfs(mol, num_confs, emb_retry)
        except Exception:
            pass  # keep whatever conf_ids we have

    if len(conf_ids) == 0:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": "Zero conformers embedded (tried standard + random coords)",
            "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    mmff_props = AllChem.MMFFGetMoleculeProperties(mol, mmffVariant="MMFF94")
    use_mmff   = mmff_props is not None
    forcefield = "MMFF94" if use_mmff else "UFF"

    conformer_dicts = []
    n_energy_fail   = 0

    for local_idx, conf_id in enumerate(conf_ids):
        try:
            ff = (
                AllChem.MMFFGetMoleculeForceField(mol, mmff_props, confId=conf_id)
                if use_mmff else
                AllChem.UFFGetMoleculeForceField(mol, confId=conf_id)
            )
            energy = float(ff.CalcEnergy())
        except Exception:
            n_energy_fail += 1
            energy = None

        xyz_path = os.path.join(xyz_out_dir, f"{inchi_key}_conf{local_idx:03d}.xyz")
        _write_xyz(mol, conf_id, xyz_path,
                   engine=f"rdkit_{forcefield}", energy=energy, energy_units="kcal/mol")

        conformer_dicts.append(_make_record(
            inchi_key  = inchi_key,
            conf_num   = local_idx,
            xyz_path   = xyz_path,
            energy     = energy,
            smiles     = smiles,
            provenance = {
                "backend":              "rdkit",
                "rdkit_version":        rdkit_version,
                "seed":                 seed,
                "threads":              cores_per_item,
                "forcefield":           forcefield,
                "generation_timestamp": timestamp,
                "source_row":           args.get("source_row"),
                "charge":               charge,
                "multiplicity":         multiplicity,
            },
        ).to_dict())

    log_details = [
        ("conformers",    len(conformer_dicts)),
        ("embedded",      len(conf_ids)),
        ("energy_failed", n_energy_fail),
        ("forcefield",    forcefield),
        ("energy_units",  "kcal/mol"),
    ]

    return {
        "item_id": inchi_key, "status": "ok",
        "log_details": log_details,
        "worker_name": worker_name, "worker_pid": worker_pid,
        "conformers": conformer_dicts,
    }


def _worker_crest(args: dict) -> dict:
    """
    Single RDKit ETKDGv3 seed → CREST iMTD-GC conformer search.
    Energy from crest_conformers.xyz comment line (absolute GFN2-xTB Ha).
    """
    worker_name = multiprocessing.current_process().name
    worker_pid  = os.getpid()

    inchi_key      = args["inchi_key"]
    smiles         = args["smiles"]
    charge         = args["charge"]
    multiplicity   = args["multiplicity"]
    seed           = args["seed"]
    cores_per_item = args["cores_per_item"]
    num_confs      = args["num_confs"]
    xyz_out_dir    = args["xyz_out_dir"]
    workdir        = args["workdir"]
    log_path       = args["log_path"]
    timestamp      = args["timestamp"]
    gfn_mode       = args.get("gfn", "gfn2")
    crest_exe      = args.get("crest_exe")
    crest_version  = args.get("crest_version")

    if not crest_exe:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": "CREST executable not found — install crest or set config['crest']['executable']",
            "log_details": [], "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    os.makedirs(xyz_out_dir, exist_ok=True)
    os.makedirs(workdir, exist_ok=True)

    # ── RDKit seed ────────────────────────────────────────────────────────────
    mol = Chem.AddHs(Chem.MolFromSmiles(smiles))
    emb = AllChem.ETKDGv3()
    emb.randomSeed           = seed
    emb.numThreads           = 1
    emb.useSmallRingTorsions = True
    emb.enforceChirality     = True

    try:
        conf_ids = AllChem.EmbedMultipleConfs(mol, 1, emb)
    except Exception as e:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": f"Seed embedding failed: {e}", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    if len(conf_ids) == 0:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": "No seed conformer embedded", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    # ── Write seed XYZ ────────────────────────────────────────────────────────
    input_xyz = os.path.join(workdir, "input.xyz")
    _write_xyz(mol, conf_ids[0], input_xyz, engine="rdkit_seed")

    # ── Run CREST ─────────────────────────────────────────────────────────────
    gfn_flag = "--gfn0" if gfn_mode == "gfn0" else "--gfn2"
    cmd = [
        crest_exe, "input.xyz", gfn_flag, "--nci",
        "--nconf",   str(num_confs),
        "--ewin",    "6",
        "--chrg",    str(charge),
        "--uhf",     str(max(0, multiplicity - 1)),
        "--nthreads", str(cores_per_item),
    ]

    LogHelper.info(log_path, f"{inchi_key} CREST cmd: {' '.join(str(c) for c in cmd)}")

    try:
        result = subprocess.run(
            cmd, cwd=workdir,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        )
    except Exception as e:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": f"CREST execution error: {e}", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    if result.returncode != 0:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": f"CREST non-zero exit ({result.returncode})", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    # ── Parse CREST output ────────────────────────────────────────────────────
    crest_xyz = os.path.join(workdir, "crest_conformers.xyz")
    if not os.path.isfile(crest_xyz):
        return {
            "item_id": inchi_key, "status": "failed",
            "error": "crest_conformers.xyz not found", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    conformer_dicts = _split_crest_xyz(
        crest_xyz     = crest_xyz,
        inchi_key     = inchi_key,
        smiles        = smiles,
        xyz_out_dir   = xyz_out_dir,
        timestamp     = timestamp,
        source_row    = args.get("source_row"),
        charge        = charge,
        multiplicity  = multiplicity,
        gfn_mode      = gfn_mode,
        crest_version = crest_version,
    )

    if not conformer_dicts:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": "No conformers parsed from CREST output", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    n_found = len(conformer_dicts)
    log_details = [
        ("conformers", n_found),
        ("requested",  num_confs),
        ("gfn",        gfn_mode),
        ("threads",    cores_per_item),
        ("energy_units", "Ha"),
    ]

    return {
        "item_id": inchi_key, "status": "ok",
        "log_details": log_details,
        "worker_name": worker_name, "worker_pid": worker_pid,
        "conformers": conformer_dicts,
    }


def _worker_openbabel(args: dict) -> dict:
    """
    RDKit ETKDGv3 seed → obabel CLI --conformer GA → MMFF94 energy via RDKit.
    Geometry is from obabel; energy evaluated without updating geometry.
    """
    worker_name = multiprocessing.current_process().name
    worker_pid  = os.getpid()

    inchi_key         = args["inchi_key"]
    smiles            = args["smiles"]
    charge            = args["charge"]
    multiplicity      = args["multiplicity"]
    seed              = args["seed"]
    num_confs         = args["num_confs"]
    xyz_out_dir       = args["xyz_out_dir"]
    workdir           = args["workdir"]
    timestamp         = args["timestamp"]
    obabel_exe        = args.get("obabel_exe")
    rdkit_version     = args.get("rdkit_version")

    if not obabel_exe:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": "obabel executable not found — install openbabel or set config['openbabel']['executable']",
            "log_details": [], "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }
    openbabel_version = args.get("openbabel_version")

    os.makedirs(xyz_out_dir, exist_ok=True)
    os.makedirs(workdir, exist_ok=True)

    # ── RDKit seed ────────────────────────────────────────────────────────────
    mol = Chem.AddHs(Chem.MolFromSmiles(smiles))
    emb = AllChem.ETKDGv3()
    emb.randomSeed           = seed
    emb.numThreads           = 1
    emb.useSmallRingTorsions = True
    emb.enforceChirality     = True

    try:
        conf_ids = AllChem.EmbedMultipleConfs(mol, 1, emb)
    except Exception as e:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": f"Seed embedding failed: {e}", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    if len(conf_ids) == 0:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": "No seed conformer embedded", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    # ── Write seed XYZ and run obabel ─────────────────────────────────────────
    seed_xyz  = os.path.join(workdir, "seed.xyz")
    multi_xyz = os.path.join(workdir, "conformers_multi.xyz")
    _write_xyz(mol, conf_ids[0], seed_xyz, engine="rdkit_seed")

    cmd = [
        obabel_exe, seed_xyz, "-O", multi_xyz,
        "--conformer", "--nconf", str(num_confs),
        "--score", "rmsd", "--writeconformers",
    ]

    try:
        result = subprocess.run(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        )
    except Exception as e:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": f"obabel execution error: {e}", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    if result.returncode != 0:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": f"obabel non-zero exit ({result.returncode})", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    if not os.path.isfile(multi_xyz):
        return {
            "item_id": inchi_key, "status": "failed",
            "error": "obabel produced no output file", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    # ── Parse multi-model XYZ ─────────────────────────────────────────────────
    ob_conformers = _parse_multimodel_xyz(multi_xyz)
    if not ob_conformers:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": "OpenBabel produced zero conformers", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    # ── MMFF94 energy evaluation on OB geometries (evaluation only) ───────────
    rdkit_mol = Chem.AddHs(Chem.MolFromSmiles(smiles))
    ob_xyz_dir = os.path.join(workdir, "xyz")
    os.makedirs(ob_xyz_dir, exist_ok=True)

    valid_conf_indices = []
    for cidx, (natoms, comment, atom_lines) in enumerate(ob_conformers):
        tmp_xyz = os.path.join(ob_xyz_dir, f"c{cidx:03d}.xyz")
        with open(tmp_xyz, "w") as f:
            f.write(f"{natoms}\n{comment}\n")
            for al in atom_lines:
                f.write(al + "\n")
        m2 = Chem.MolFromXYZFile(tmp_xyz)
        if m2 is not None:
            rdkit_mol.AddConformer(m2.GetConformer(), assignId=True)
            valid_conf_indices.append(cidx)

    if not valid_conf_indices:
        return {
            "item_id": inchi_key, "status": "failed",
            "error": "No OB conformers loadable by RDKit", "log_details": [],
            "worker_name": worker_name, "worker_pid": worker_pid,
            "conformers": [],
        }

    mmff_props_mol = AllChem.MMFFGetMoleculeProperties(rdkit_mol, mmffVariant="MMFF94")
    use_mmff       = mmff_props_mol is not None
    forcefield     = "MMFF94" if use_mmff else "UFF"
    conformer_dicts = []
    n_energy_fail   = 0

    for local_idx, orig_cidx in enumerate(valid_conf_indices):
        try:
            ff = (
                AllChem.MMFFGetMoleculeForceField(rdkit_mol, mmff_props_mol, confId=local_idx)
                if use_mmff else
                AllChem.UFFGetMoleculeForceField(rdkit_mol, confId=local_idx)
            )
            energy = float(ff.CalcEnergy())
        except Exception:
            n_energy_fail += 1
            energy = None

        xyz_path = os.path.join(xyz_out_dir, f"{inchi_key}_conf{local_idx:03d}.xyz")
        _write_xyz(rdkit_mol, local_idx, xyz_path,
                   engine=f"openbabel_{forcefield}", energy=energy, energy_units="kcal/mol")

        conformer_dicts.append(_make_record(
            inchi_key  = inchi_key,
            conf_num   = local_idx,
            xyz_path   = xyz_path,
            energy     = energy,
            smiles     = smiles,
            provenance = {
                "backend":              "openbabel",
                "openbabel_version":    openbabel_version,
                "rdkit_version":        rdkit_version,
                "forcefield":           forcefield,
                "seed":                 seed,
                "generation_timestamp": timestamp,
                "source_row":           args.get("source_row"),
                "charge":               charge,
                "multiplicity":         multiplicity,
            },
        ).to_dict())

    log_details = [
        ("conformers",    len(conformer_dicts)),
        ("ob_generated",  len(ob_conformers)),
        ("energy_failed", n_energy_fail),
        ("forcefield",    forcefield),
        ("energy_units",  "kcal/mol"),
    ]

    return {
        "item_id": inchi_key, "status": "ok",
        "log_details": log_details,
        "worker_name": worker_name, "worker_pid": worker_pid,
        "conformers": conformer_dicts,
    }


# =============================================================================
# Stage class
# =============================================================================

class GenerationStage(BaseStage):
    """
    Conformer generation stage.

    Parallel execution via BaseStage.run_parallel().  All backends dispatch
    through the module-level _generation_worker() entry point.

    parallel[engine]=false in generation_defaults.json forces n_workers=1
    (single-worker pool, effectively serial) without changing code paths.
    """

    # =========================================================================
    # Entry point
    # =========================================================================

    def execute(self):
        self._load_stage_config()
        self.set_stage_output("energies.json")

        stage_input = self.get_stage_input()
        self.require_file(stage_input, "cleaned dataset")

        # Copy cleaned.csv into inputs/ for reproducibility
        inputs_cleaned = os.path.join(self.inputs_dir, "cleaned.csv")
        os.makedirs(self.inputs_dir, exist_ok=True)
        if os.path.abspath(stage_input) != os.path.abspath(inputs_cleaned):
            shutil.copy(stage_input, inputs_cleaned)
        self.log_info(f"Stage input: {stage_input}")

        engine = self.engine
        if engine not in GENERATION_BACKENDS:
            self.fail(
                f"Unknown generation engine: '{engine}'. "
                f"Valid: {list(GENERATION_BACKENDS)}"
            )

        # ── Adjust allocated resources using per-backend config ───────────────
        engine_cores_cap = self.cores_per_item_cfg.get(engine, 1)
        self.cores_per_item = min(self.cores_per_item, engine_cores_cap)

        if not self.parallel_cfg.get(engine, False):
            self.n_workers = 1

        self.log_config(
            f"engine={engine}  seed={self.seed}  gfn={self.gfn}  "
            f"strict={self.strict_mode}  "
            f"global_fail_threshold={self.global_fail_threshold}"
        )
        self.log_config(
            f"cores_per_item={self.cores_per_item}  "
            f"n_workers={self.n_workers}  "
            f"parallel={self.parallel_cfg.get(engine, False)}"
        )

        # ── Prepare ───────────────────────────────────────────────────────────
        self._xyz_dir = os.path.join(self.outputs_dir, "xyz")
        os.makedirs(self._xyz_dir, exist_ok=True)

        df_all = self._load_csv(stage_input)
        self._metadata_index = self._load_metadata_index()
        valid_rows = self._validate_rows(df_all)

        if not valid_rows:
            self.fail("No valid molecules found in cleaned dataset.")

        # Resolve num_confs before registering items
        num_confs = self.parameters.get("n")
        if num_confs is None:
            num_confs = self._default_num_confs(valid_rows)
            self.log_info(f"Conformer count heuristic: n={num_confs}")
        else:
            self.log_info(f"Conformer count (explicit): n={num_confs}")
        self._num_confs = num_confs

        # Store valid_rows keyed by inchi_key for _build_args lookup
        self._valid_rows_map = {ik: (idx, smiles, row)
                                for idx, ik, smiles, row in valid_rows}

        inchi_keys = list(self._valid_rows_map.keys())
        self.set_items(inchi_keys)

        # Version strings for provenance
        self._rdkit_version     = getattr(Chem, "__version__", None)
        self._crest_version     = self._get_crest_version()
        self._openbabel_version = self._get_openbabel_version()
        self._timestamp         = datetime.utcnow().isoformat() + "Z"

        # ── Run ───────────────────────────────────────────────────────────────
        self.run_parallel(_generation_worker, self._build_args)

        # ── Threshold check ───────────────────────────────────────────────────
        n_items  = len(self.job.items)
        n_failed = len(self.job.failed_items)
        if n_items > 0 and n_failed / n_items > self.global_fail_threshold:
            self.fail(
                f"Too many failures: {n_failed}/{n_items} "
                f"exceeded global_fail_threshold={self.global_fail_threshold}"
            )

        # ── Assemble output ───────────────────────────────────────────────────
        self._assemble_output(engine=engine, num_confs=num_confs,
                              num_valid=len(inchi_keys), total_rows=len(df_all))

    # =========================================================================
    # Config loading
    # =========================================================================

    def _load_stage_config(self):
        """
        Resolve generation config. Hierarchy per field (highest wins):
          1. parameters (pipeline spec args — runtime override)
          2. generation_defaults.json
          3. hardcoded fallback
        """
        # Load defaults file
        defaults_path = (
            self.config
            .get("generation", {})
            .get("defaults")
        )
        defaults = {}
        if defaults_path and os.path.isfile(defaults_path):
            try:
                with open(defaults_path) as f:
                    defaults = json.load(f)
            except Exception as e:
                self.log_warning(f"Could not read generation_defaults.json: {e}")
        else:
            self.log_warning("generation_defaults.json not found — using hardcoded defaults")

        params = self.parameters

        self.engine    = params.get("engine") or defaults.get("engine", "rdkit")
        self.seed      = int(params.get("seed") or defaults.get("seed", 42))
        self.gfn       = (params.get("gfn") or defaults.get("gfn", "gfn2")).lower()
        self.strict_mode = bool(
            params.get("strict") if params.get("strict") is not None
            else defaults.get("strict", False)
        )
        self.global_fail_threshold = float(
            params.get("global_fail_threshold")
            if params.get("global_fail_threshold") is not None
            else defaults.get("global_fail_threshold", 0.8)
        )

        # Per-backend dicts — pipeline spec cannot override these as flat values,
        # but can supply a full replacement dict under the same keys.
        self.cores_per_item_cfg = (
            params.get("cores_per_item")
            if isinstance(params.get("cores_per_item"), dict)
            else defaults.get("cores_per_item", {"rdkit": 1, "crest": 4, "openbabel": 1})
        )
        self.parallel_cfg = (
            params.get("parallel")
            if isinstance(params.get("parallel"), dict)
            else defaults.get("parallel", {"rdkit": False, "crest": True, "openbabel": False})
        )

    # =========================================================================
    # args builder — called once per item by run_parallel
    # =========================================================================

    def _build_args(self, inchi_key: str) -> dict:
        """Build the fully self-contained args dict for one molecule."""
        idx, smiles, row = self._valid_rows_map[inchi_key]
        charge, multiplicity, charge_source, multiplicity_source = self._get_charge_multiplicity(inchi_key, self._metadata_index)

        log_fn = self.log_warning if "default" in (charge_source, multiplicity_source) else self.log_info
        log_fn(
            f"[CHARGE] {inchi_key}: charge={charge} ({charge_source}), "
            f"multiplicity={multiplicity} ({multiplicity_source})"
        )

        args = self._base_args(inchi_key)
        args.update({
            "engine":        self.engine,
            "inchi_key":     inchi_key,
            "smiles":        smiles,
            "charge":        charge,
            "multiplicity":  multiplicity,
            "seed":          self.seed,
            "gfn":           self.gfn,
            "num_confs":     self._num_confs,
            "xyz_out_dir":   self._xyz_dir,
            "timestamp":     self._timestamp,
            "source_row":    int(idx),
            "rdkit_version":     self._rdkit_version,
            "crest_version":     self._crest_version,
            "openbabel_version": self._openbabel_version,
        })

        # Tool paths — only needed by the relevant backend, harmless to others
        crest_exe = self._resolve_crest_exe()
        if crest_exe:
            args["crest_exe"] = crest_exe

        obabel_exe = self._resolve_obabel_exe()
        if obabel_exe:
            args["obabel_exe"] = obabel_exe

        return args

    # =========================================================================
    # Output assembly — runs after run_parallel, reads checkpoints
    # =========================================================================

    def _assemble_output(self, engine, num_confs, num_valid, total_rows):
        """Reconstruct ConformerSet from checkpoints and write stage outputs."""
        checkpoints = self._load_all_checkpoints()
        conformer_set = ConformerSet()

        for cp in checkpoints:
            for rec_dict in cp.get("conformers", []):
                try:
                    record = ConformerRecord.from_dict(rec_dict)
                    conformer_set.add(record)
                except Exception as e:
                    self.log_warning(f"Could not restore conformer from checkpoint: {e}")

        if len(conformer_set) == 0:
            self.fail("Generation produced zero conformers across all molecules.")

        # energies.json (canonical stage output)
        energies_path = self.get_stage_output()
        conformer_set.save(energies_path)

        # summary.csv
        summary_path = os.path.join(self.outputs_dir, "summary.csv")
        with AtomicWriter(summary_path) as f:
            pd.DataFrame(conformer_set.to_list()).to_csv(f, index=False)

        # generation_metadata.json
        meta_path = os.path.join(self.outputs_dir, "generation_metadata.json")
        with AtomicWriter(meta_path) as f:
            json.dump({
                "stage":               "generation",
                "engine":              engine,
                "num_valid_molecules": num_valid,
                "num_total_rows":      total_rows,
                "num_conformers":      len(conformer_set),
                "num_confs_requested": num_confs,
                "seed":                self.seed,
                "timestamp":           datetime.utcnow().isoformat() + "Z",
            }, f, indent=2)

        self.log_info(
            f"Outputs: energies.json ({len(conformer_set)} conformers), "
            f"summary.csv, generation_metadata.json"
        )

    # =========================================================================
    # Input loading
    # =========================================================================

    def _load_csv(self, path: str) -> pd.DataFrame:
        try:
            df = pd.read_csv(path)
        except Exception as e:
            self.fail(f"Failed to load stage_input {path}: {e}")
        self.log_info(f"Loaded {len(df)} rows")
        return df

    def _validate_rows(self, df: pd.DataFrame) -> list:
        """
        Validate each row has a valid inchi_key and parseable SMILES.
        Returns list of (row_idx, inchi_key, smiles_canon, row).
        Deduplicates to one entry per inchi_key.
        """
        seen  = {}
        valid = []

        for idx, row in df.iterrows():
            ik     = row.get("inchi_key")
            smiles = row.get("smiles")

            if not ik or not isinstance(ik, str) or not ik.strip():
                self.log_warning(f"Row {idx}: missing inchi_key — skipped")
                if self.strict_mode:
                    self.fail(f"Row {idx}: missing inchi_key")
                continue

            if not smiles:
                self.log_warning(f"Row {idx} ({ik}): missing SMILES — skipped")
                if self.strict_mode:
                    self.fail(f"Row {idx}: missing SMILES")
                continue

            mol = Chem.MolFromSmiles(str(smiles))
            if mol is None:
                self.log_warning(f"Row {idx} ({ik}): invalid SMILES '{smiles}' — skipped")
                if self.strict_mode:
                    self.fail(f"Row {idx}: invalid SMILES")
                continue

            if ik in seen:
                continue

            smiles_canon = Chem.MolToSmiles(mol, canonical=True)
            seen[ik] = idx
            valid.append((idx, ik, smiles_canon, row))

        self.log_info(f"Valid unique molecules: {len(valid)}")
        return valid

    # =========================================================================
    # Metadata
    # =========================================================================

    def _load_metadata_index(self) -> dict:
        """Load per-molecule metadata from constant_files.metadata_dir."""
        metadata_index = {}
        meta_dir = self.config.get("constant_files", {}).get("metadata_dir")

        if not meta_dir or not os.path.isdir(meta_dir):
            self.log_warning("No metadata_dir found — using defaults: charge=0, multiplicity=1")
            return metadata_index

        for fname in os.listdir(meta_dir):
            if not fname.endswith(".json"):
                continue
            ik = fname[:-5]
            try:
                with open(os.path.join(meta_dir, fname)) as f:
                    metadata_index[ik] = json.load(f)
            except Exception as e:
                self.log_warning(f"Could not read metadata for {ik}: {e}")

        self.log_info(f"Loaded metadata for {len(metadata_index)} molecules")
        return metadata_index

    def _get_charge_multiplicity(self, inchi_key: str, metadata_index: dict) -> tuple[int, int, str, str]:
        """Resolve charge and multiplicity. Hierarchy: parameters > metadata > defaults."""
        params = self.parameters
        meta   = metadata_index.get(inchi_key, {})
        charge = (
            params.get("charge") if params.get("charge") is not None
            else meta.get("charge", 0)
        )
        charge_source = "user_param" if params.get("charge") is not None else meta.get("charge_source", "default")
        multiplicity = (
            params.get("multiplicity") if params.get("multiplicity") is not None
            else meta.get("multiplicity", 1)
        )
        multiplicity_source = "user_param" if params.get("multiplicity") is not None else meta.get("multiplicity_source", "default")
        return int(charge), int(multiplicity), charge_source, multiplicity_source

    # =========================================================================
    # Conformer count heuristic
    # =========================================================================

    def _default_num_confs(self, valid_rows: list) -> int:
        """O'Boyle 2011 heuristic by rotatable bond count (max across dataset)."""
        max_n = 0
        for _, _, smiles, _ in valid_rows:
            mol = Chem.MolFromSmiles(smiles)
            if mol is None:
                continue
            try:
                mol = Chem.RemoveHs(mol)
            except Exception:
                pass
            try:
                n_rot = rdMolDescriptors.CalcNumRotatableBonds(mol)
            except Exception:
                n_rot = 8
            n = 50 if n_rot <= 7 else (200 if n_rot <= 12 else 300)
            max_n = max(max_n, n)
        return max_n if max_n > 0 else 50

    # =========================================================================
    # Tool resolution
    # =========================================================================

    def _resolve_crest_exe(self) -> str | None:
        exe = self.config.get("crest", {}).get("executable")
        if exe and os.path.isfile(exe):
            return exe
        return shutil.which("crest")

    def _resolve_obabel_exe(self) -> str | None:
        cfg_exe = self.config.get("openbabel", {}).get("executable")
        if cfg_exe and os.path.isfile(cfg_exe):
            return cfg_exe
        return shutil.which("obabel")

    def _get_crest_version(self) -> str | None:
        exe = self._resolve_crest_exe()
        if not exe:
            return None
        try:
            r = subprocess.run(
                [exe, "--version"],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
            )
            if r.returncode == 0:
                return r.stdout.strip().splitlines()[0].strip()
        except Exception:
            pass
        return None

    def _get_openbabel_version(self) -> str | None:
        exe = self._resolve_obabel_exe()
        if not exe:
            return None
        try:
            r = subprocess.run(
                [exe, "--version"],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
            )
            output = (r.stdout + r.stderr).strip()
            if output:
                return output.splitlines()[0].strip()
        except Exception:
            pass
        return None
