"""
tests/stages/test_pruning_rdkit_post_opt_legacy.py

Unit tests for PruningStage._prune_rdkit_post_opt_legacy().

Verifies that the 4 IC-pipeline filters are applied correctly:
  1. Convergence  — remove if MMFF status != "converged"
  2. Overlap      — remove if any atom pair < 0.1 Å
  3. Boltzmann    — remove if rel_prob < 1% at 298.15 K (~2.73 kcal/mol cutoff)
  4. RMSD 1.0 Å   — cluster, lower-energy conformer survives

Run with:
    cd /home/lunet/cglh4/openCOSMO-RS_Pipeline-LH
    pytest tests/stages/test_pruning_rdkit_post_opt_legacy.py -v
"""

import math
import os
import textwrap
from unittest.mock import MagicMock, call, patch

import pytest

from modules.stages.pruning_stage import PruningStage
from modules.utils.conformers import ConformerRecord


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

RT_KCAL = 8.314 * 298.15 / 4184.0   # ≈ 0.5927 kcal/mol


def _boltzmann_cutoff_kcal():
    """Maximum ΔE that survives the 1% Boltzmann cutoff (rel_prob ≥ 0.01)."""
    return -math.log(0.01) * RT_KCAL   # ≈ 2.73 kcal/mol


def _make_stage() -> PruningStage:
    """Return a PruningStage instance with log methods mocked out."""
    stage = PruningStage.__new__(PruningStage)
    stage.log_info    = MagicMock()
    stage.log_warning = MagicMock()
    stage.log_error   = MagicMock()
    return stage


def _make_rec(
    tmp_path,
    conf_num: int,
    energy: float,
    status: str = "converged",
    xyz_content: str | None = None,
) -> ConformerRecord:
    """
    Build a minimal ConformerRecord with an XYZ file on disk.

    Default XYZ is a 3-atom water-like triangle with normal geometry.
    """
    if xyz_content is None:
        xyz_content = textwrap.dedent("""\
            3
            Generated by test
            O  0.000  0.000  0.000
            H  0.957  0.000  0.000
            H -0.240  0.927  0.000
        """)

    xyz_path = tmp_path / f"conf{conf_num:03d}.xyz"
    xyz_path.write_text(xyz_content)

    return ConformerRecord(
        inchi_key="TESTMOLECULE-UHFFFAOYSA-N",
        conf_num=conf_num,
        xyz_path=str(xyz_path),
        energy=energy,
        smiles="O",
        optimisation_history=[
            {"stage": "optimisation", "engine": "forcefield_mmff", "status": status}
        ],
    )


# ─────────────────────────────────────────────────────────────────────────────
# Convergence filter
# ─────────────────────────────────────────────────────────────────────────────

class TestConvergenceFilter:

    def test_removes_partial(self, tmp_path):
        stage = _make_stage()
        recs = [
            _make_rec(tmp_path, 0, 1.0, status="converged"),
            _make_rec(tmp_path, 1, 2.0, status="partial"),
        ]
        result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        ids = [r.conf_num for r in result]
        assert 0 in ids
        assert 1 not in ids

    def test_removes_failed(self, tmp_path):
        stage = _make_stage()
        recs = [
            _make_rec(tmp_path, 0, 1.0, status="converged"),
            _make_rec(tmp_path, 1, 2.0, status="failed"),
        ]
        result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        assert len(result) == 1
        assert result[0].conf_num == 0

    def test_keeps_all_converged(self, tmp_path):
        stage = _make_stage()
        recs = [_make_rec(tmp_path, i, float(i), status="converged") for i in range(3)]
        # Bypass RMSD — all 3 share the same default XYZ, so without mocking
        # the RMSD filter would collapse them to 1. We test convergence only here.
        with patch.object(stage, '_prune_rmsd', side_effect=lambda c, rmsd_threshold: c):
            result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        assert len(result) == 3

    def test_no_history_treated_as_unknown(self, tmp_path):
        stage = _make_stage()
        rec = _make_rec(tmp_path, 0, 1.0)
        rec.optimisation_history = []
        result = stage._prune_rdkit_post_opt_legacy([rec], enabled=True)
        assert result == []

    def test_disabled_returns_all(self, tmp_path):
        stage = _make_stage()
        recs = [_make_rec(tmp_path, i, float(i), status="failed") for i in range(3)]
        result = stage._prune_rdkit_post_opt_legacy(recs, enabled=False)
        assert len(result) == 3


# ─────────────────────────────────────────────────────────────────────────────
# Overlapping atoms filter
# ─────────────────────────────────────────────────────────────────────────────

class TestOverlapFilter:

    # XYZ with two atoms 0.05 Å apart — well below the 0.1 Å threshold
    OVERLAPPING_XYZ = textwrap.dedent("""\
        3
        overlapping test
        O  0.000  0.000  0.000
        H  0.050  0.000  0.000
        H -0.240  0.927  0.000
    """)

    def test_removes_overlapping_conformer(self, tmp_path):
        stage = _make_stage()
        recs = [
            _make_rec(tmp_path, 0, 1.0),
            _make_rec(tmp_path, 1, 2.0, xyz_content=self.OVERLAPPING_XYZ),
        ]
        result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        ids = [r.conf_num for r in result]
        assert 0 in ids
        assert 1 not in ids

    def test_keeps_normal_geometry(self, tmp_path):
        stage = _make_stage()
        recs = [_make_rec(tmp_path, 0, 1.0)]
        result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        assert len(result) == 1


# ─────────────────────────────────────────────────────────────────────────────
# Boltzmann filter
# ─────────────────────────────────────────────────────────────────────────────

class TestBoltzmannFilter:

    def test_keeps_minimum_energy(self, tmp_path):
        stage = _make_stage()
        recs = [_make_rec(tmp_path, 0, 0.0)]
        result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        assert len(result) == 1

    def test_removes_conformer_above_cutoff(self, tmp_path):
        """4.0 kcal/mol above minimum — rel_prob ≈ 0.001 < 0.01 → removed."""
        stage = _make_stage()
        recs = [
            _make_rec(tmp_path, 0, 0.0),
            _make_rec(tmp_path, 1, 4.0),
        ]
        result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        ids = [r.conf_num for r in result]
        assert 0 in ids
        assert 1 not in ids

    def test_keeps_conformer_below_cutoff(self, tmp_path):
        """2.0 kcal/mol above minimum — rel_prob > 0.01 → kept."""
        stage = _make_stage()
        recs = [
            _make_rec(tmp_path, 0, 0.0),
            _make_rec(tmp_path, 1, 2.0),
        ]
        # Both conformers share the same default XYZ; bypass RMSD so it doesn't
        # collapse them — we're testing Boltzmann only here.
        with patch.object(stage, '_prune_rmsd', side_effect=lambda c, rmsd_threshold: c):
            result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        assert len(result) == 2

    def test_boundary_just_inside_cutoff(self, tmp_path):
        """ΔE = cutoff - ε → just survives."""
        cutoff = _boltzmann_cutoff_kcal()
        stage  = _make_stage()
        recs   = [
            _make_rec(tmp_path, 0, 0.0),
            _make_rec(tmp_path, 1, cutoff - 0.01),
        ]
        with patch.object(stage, '_prune_rmsd', side_effect=lambda c, rmsd_threshold: c):
            result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        assert len(result) == 2

    def test_boundary_just_outside_cutoff(self, tmp_path):
        """ΔE = cutoff + ε → removed."""
        cutoff = _boltzmann_cutoff_kcal()
        stage  = _make_stage()
        recs   = [
            _make_rec(tmp_path, 0, 0.0),
            _make_rec(tmp_path, 1, cutoff + 0.01),
        ]
        result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        assert len(result) == 1
        assert result[0].conf_num == 0


# ─────────────────────────────────────────────────────────────────────────────
# RMSD filter (delegates to _prune_rmsd with threshold=1.0)
# ─────────────────────────────────────────────────────────────────────────────

class TestRmsdFilter:

    # Two conformers with very similar geometry (tiny displacement — RMSD << 1.0)
    XYZ_A = textwrap.dedent("""\
        3
        conf A
        O  0.000  0.000  0.000
        H  0.957  0.000  0.000
        H -0.240  0.927  0.000
    """)
    XYZ_B = textwrap.dedent("""\
        3
        conf B (displaced by 0.1 Å — RMSD well below 1.0)
        O  0.100  0.000  0.000
        H  1.057  0.000  0.000
        H -0.140  0.927  0.000
    """)

    def test_keeps_lower_energy_when_similar(self, tmp_path):
        """Two near-identical conformers → lower energy (conf 0) survives."""
        stage = _make_stage()
        recs = [
            _make_rec(tmp_path, 0, 1.0, xyz_content=self.XYZ_A),  # lower energy
            _make_rec(tmp_path, 1, 2.0, xyz_content=self.XYZ_B),  # higher energy, similar
        ]
        result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        assert len(result) == 1
        assert result[0].conf_num == 0

    def test_rmsd_called_with_threshold_1_0(self, tmp_path):
        """Verifies RMSD filter is delegated to _prune_rmsd with threshold=1.0 Å."""
        stage = _make_stage()
        recs  = [_make_rec(tmp_path, 0, 0.0)]
        with patch.object(stage, '_prune_rmsd', return_value=recs) as mock_rmsd:
            stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        mock_rmsd.assert_called_once_with(recs, rmsd_threshold=1.0)

    def test_distinct_conformers_both_survive(self, tmp_path):
        """When _prune_rmsd retains both (RMSD > threshold), both survive."""
        stage = _make_stage()
        rec0  = _make_rec(tmp_path, 0, 1.0)
        rec1  = _make_rec(tmp_path, 1, 2.0)
        with patch.object(stage, '_prune_rmsd', side_effect=lambda c, rmsd_threshold: c):
            result = stage._prune_rdkit_post_opt_legacy([rec0, rec1], enabled=True)
        assert len(result) == 2


# ─────────────────────────────────────────────────────────────────────────────
# Combined filter (realistic mixed set)
# ─────────────────────────────────────────────────────────────────────────────

class TestCombined:

    OVERLAPPING_XYZ = textwrap.dedent("""\
        3
        overlapping
        O  0.000  0.000  0.000
        H  0.050  0.000  0.000
        H -0.240  0.927  0.000
    """)

    def test_filters_applied_in_order(self, tmp_path):
        """
        Input: 5 conformers
          conf0 — converged, E=0.0, normal geom     → survives all filters
          conf1 — partial,   E=0.5                  → removed by convergence
          conf2 — converged, E=0.1, overlapping     → removed by overlap
          conf3 — converged, E=4.0, normal geom     → removed by Boltzmann
          conf4 — converged, E=0.2, similar to conf0 (RMSD < 1.0) → removed by RMSD

        Expected survivors: conf0 only.
        """
        stage = _make_stage()

        # Near-identical to conf0 (same atoms, tiny displacement)
        xyz_similar = textwrap.dedent("""\
            3
            similar to conf0
            O  0.050  0.000  0.000
            H  1.007  0.000  0.000
            H -0.190  0.927  0.000
        """)

        recs = [
            _make_rec(tmp_path, 0, 0.0, status="converged"),
            _make_rec(tmp_path, 1, 0.5, status="partial"),
            _make_rec(tmp_path, 2, 0.1, status="converged",
                      xyz_content=self.OVERLAPPING_XYZ),
            _make_rec(tmp_path, 3, 4.0, status="converged"),
            _make_rec(tmp_path, 4, 0.2, status="converged",
                      xyz_content=xyz_similar),
        ]

        result = stage._prune_rdkit_post_opt_legacy(recs, enabled=True)
        assert len(result) == 1
        assert result[0].conf_num == 0
